swagger: "2.0"
info:
  contact:
    name: vjs
  title: WAN-WAN-GO-BE
  version: 0.0.1
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
  - https
paths:
  /:
    get:
      tags: Hello World
      description: Hello World
      responses:
        200:
          description: success response
          schema:
            $ref: "#/definitions/response"
  /getData:
    get:
      tags:
        - Get Data
      description: Get Data Handler
      responses:
        200:
          description: success response
          schema:
            $ref: "#/definitions/response"
  /getThreadPage:
    get:
      tags:
        - Get Thread for Forum - Home
      description: Get Data Handler
      responses:
        200:
          description: success response
          schema:
            $ref: "#/definitions/response"
  /getThreadCategoryPage:
    get:
      tags:
        - Get Thread for Forum - Category
      description: Get Data Handler
      parameters:
        - name: ThreadCategoryRequest
          in: body
          schema:
            type: "#/definitions/requestThreadCategoryPage"
      responses:
        200:
          description: success response
          schema:
            $ref: "#/definitions/response"
  /getThreadDetail:
    get:
      tags:
        - Get Thread Detail for Forum
      description: Get Data Handler
      parameters:
        - in: query
          name: threadId
          type: string
        - in: query
          name: page
          type: int
      responses:
        200:
          description: success response
          schema:
            $ref: "#/definitions/response"
definitions:
  "response":
    "type": "object"
    "properties":
      "res":
        "type": "string"
        "format": "string"
  "requestThreadCategoryPage":
    "type": "object"
    "properties":
      "res":
        "type": "string"
        "format": "ThreadCategoryRequest"